apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: elasticsearch-communication
  namespace: logging-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: log-processor
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: log-analyzer
      ports:
        - protocol: TCP
          port: 9200
        - protocol: TCP
          port: 9300
